# Generated by Django 3.1.1 on 2021-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.BooleanField()),
                ('task', models.CharField(max_length=100)),
                ('limit', models.DateField()),
                ('memo', models.CharField(max_length=500)),
            ],
        ),
    ]
